//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAG_TeknikResimDamgalama.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("816, 489")]
        public global::System.Drawing.Size Form1Size {
            get {
                return ((global::System.Drawing.Size)(this["Form1Size"]));
            }
            set {
                this["Form1Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("247")]
        public int splitContainer1SplitterDistance {
            get {
                return ((int)(this["splitContainer1SplitterDistance"]));
            }
            set {
                this["splitContainer1SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("161")]
        public int splitContainer2SplitterDistance {
            get {
                return ((int)(this["splitContainer2SplitterDistance"]));
            }
            set {
                this["splitContainer2SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 8.25pt, style=Bold")]
        public global::System.Drawing.Font Form2textBox1Font {
            get {
                return ((global::System.Drawing.Font)(this["Form2textBox1Font"]));
            }
            set {
                this["Form2textBox1Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Form2comboBox1SelectedIndex {
            get {
                return ((int)(this["Form2comboBox1SelectedIndex"]));
            }
            set {
                this["Form2comboBox1SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Form2panel1BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Form2panel1BackColor"]));
            }
            set {
                this["Form2panel1BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string Form2textBox3Text {
            get {
                return ((string)(this["Form2textBox3Text"]));
            }
            set {
                this["Form2textBox3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string Form2textBox2Text {
            get {
                return ((string)(this["Form2textBox2Text"]));
            }
            set {
                this["Form2textBox2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color Form2panel2BackColor {
            get {
                return ((global::System.Drawing.Color)(this["Form2panel2BackColor"]));
            }
            set {
                this["Form2panel2BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Form2textBox1Color {
            get {
                return ((global::System.Drawing.Color)(this["Form2textBox1Color"]));
            }
            set {
                this["Form2textBox1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("575, 448")]
        public global::System.Drawing.Size Form2Size {
            get {
                return ((global::System.Drawing.Size)(this["Form2Size"]));
            }
            set {
                this["Form2Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Form2splitContainer1SplitterDistance {
            get {
                return ((int)(this["Form2splitContainer1SplitterDistance"]));
            }
            set {
                this["Form2splitContainer1SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PdfiumDllPath {
            get {
                return ((string)(this["PdfiumDllPath"]));
            }
            set {
                this["PdfiumDllPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ins")]
        public global::System.Windows.Forms.Keys Form2InsertKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Form2InsertKey"]));
            }
            set {
                this["Form2InsertKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Del")]
        public global::System.Windows.Forms.Keys Form2DeleteKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Form2DeleteKey"]));
            }
            set {
                this["Form2DeleteKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Form2NoText {
            get {
                return ((bool)(this["Form2NoText"]));
            }
            set {
                this["Form2NoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Form2NoShape {
            get {
                return ((bool)(this["Form2NoShape"]));
            }
            set {
                this["Form2NoShape"] = value;
            }
        }
    }
}
